edge/nodejs/modify-response-status-code/modify-response-status-code/app.js

pr test commit

---

.github/workflows/nodejs-ci.yaml
.github/workflows/python-ci.yaml
scripts/nodejs-ci-build-coverage.sh

change aws access key and secret key for CI process

---

templates/aws-cloudfront-waf/lib/aws-cloudfront-waf-main.ts

Use parameter as a global lambda scope variable
cdk deploy test
*[] My testing has passed*
----

fix: Use parameter for lambda scope variable

---

edge/nodejs/multiple-origin-IP-retry/template.yaml

fix: multiple-origin-IP-retry-source-code-url

---

docs/security/deploy/README.en.md
templates/aws-cloudfront-waf/deployment/build-s3-dist.sh

feat: rename build lambda script

---

edge/nodejs/serving-based-on-device/template.yaml

#112 
change function timeout for viewer request event type
no
no
----

fix: serving-based-on-device function timeout

---

function/js/add-security-headers-cloudfront-function/README.md
function/js/add-security-headers-cloudfront-function/template.yaml

Update readme & description for add-security-headers-cff
----

Update readme & description for add-security-headers-cff

---

templates/aws-cloudfront-waf/lib/aws-cloudfront-waf-main.ts

fixed: fixed glue encryption for cdk upgraded

---

.cfnnag_global_suppress_list
templates/aws-cloudfront-monitoring/README.md
templates/aws-cloudfront-monitoring/deployment/build-s3-dist.sh
templates/aws-cloudfront-monitoring/deployment/helper.py
templates/aws-cloudfront-monitoring/deployment/run-unit-tests.sh
templates/aws-cloudfront-monitoring/source/cdk.json
templates/aws-cloudfront-monitoring/source/jest.config.js
templates/aws-cloudfront-monitoring/source/package.json
templates/aws-cloudfront-monitoring/source/templates/bin/aws-cloudfront-monitoring-main.ts
templates/aws-cloudfront-monitoring/source/templates/lib/aws-cloudfront-monitoring-stack.ts
templates/aws-cloudfront-monitoring/source/templates/test/aws-cloudfront-monitoring.test.ts
templates/aws-cloudfront-monitoring/tsconfig.json

adding monitoring stack related CDK code to main branch

---

edge/nodejs/modify-response-status-code/modify-response-status-code/tests/test_metric_manager.py
templates/aws-cloudfront-monitoring/source/lambda.d/add_partition/add_partition.py
templates/aws-cloudfront-monitoring/source/lambda.d/add_partition/test_add_partition.py
templates/aws-cloudfront-monitoring/source/lambda.d/delete_partition/delete_partition.py
templates/aws-cloudfront-monitoring/source/lambda.d/delete_partition/test_delete_partition.py
templates/aws-cloudfront-monitoring/source/lambda.d/metric_manager/metric_manager.py
templates/aws-cloudfront-monitoring/source/lambda.d/metric_manager/test_metric_manager.py
templates/aws-cloudfront-monitoring/source/lambda.d/shared_lib/python/metric_helper.py
templates/aws-cloudfront-monitoring/source/lambda.d/shared_lib/python/test_metric_helper.py
templates/aws-cloudfront-monitoring/source/requirements-dev.txt
templates/aws-cloudfront-monitoring/source/templates/test/aws-cloudfront-monitoring.test.ts

Adding some Unit Test for lambda and lambda layer functions
Adding some Unit Test for lambda and lambda layer functions
Local Run pytest
All local unit test passed
----

Adding some Unit Test for lambda and lambda layer functions

---

templates/aws-cloudfront-monitoring/source/lambda.d/metric_collector_bandwidth_cdn/metric_collector_bandwidth_cdn.py
templates/aws-cloudfront-monitoring/source/lambda.d/metric_collector_bandwidth_origin/metric_collector_bandwidth_origin.py
templates/aws-cloudfront-monitoring/source/lambda.d/metric_collector_chr_bandwidth/metric_collector_chr_bandwidth.py
templates/aws-cloudfront-monitoring/source/lambda.d/metric_collector_chr_request/metric_collector_chr_request.py
templates/aws-cloudfront-monitoring/source/lambda.d/metric_collector_request_cdn/metric_collector_request_cdn.py
templates/aws-cloudfront-monitoring/source/lambda.d/metric_collector_request_origin/metric_collector_request_origin.py
templates/aws-cloudfront-monitoring/source/lambda.d/metric_collector_status_code_cdn/metric_collector_status_code_cdn.py
templates/aws-cloudfront-monitoring/source/lambda.d/metric_collector_status_code_origin/metric_collector_status_code_origin.py
templates/aws-cloudfront-monitoring/source/lambda.d/shared_lib/python/metric_helper.py

Update sql to improve perf
Integration test passed
----

chore: improve perf

---

docs-ig/en/monitoring/non-real-time-monitoring.md
docs-ig/zh/monitoring/non-real-time-monitoring.md

doc: add steps to activate standard log

---

edge/nodejs/access-origin-by-weight-rate/template.yaml
edge/nodejs/add-security-headers/template.yaml
edge/nodejs/anti-hotlinking/template.yaml
edge/nodejs/authentication-with-aliyun-cdn-typeA/template.yaml
edge/nodejs/authentication-with-cognito/template.yaml
edge/nodejs/bot-detection/template.yaml
edge/nodejs/cross-origin-resource-sharing/template.yaml
edge/nodejs/custom-response-with-replaced-url/template.yaml
edge/nodejs/http302-from-origin/template.yaml
edge/nodejs/modify-response-header/template.yaml
edge/nodejs/modify-response-status-code/template.yaml
edge/nodejs/multiple-origin-IP-retry/template.yaml
edge/nodejs/normalize-query-string/template.yaml
edge/nodejs/resize-picture/template.yaml
edge/nodejs/rewrite-url/template.yaml
edge/nodejs/serving-based-on-device/template.yaml
edge/nodejs/simple-lambda-edge/template.yaml
website/static/template/template.yaml

https://github.com/awslabs/aws-cloudfront-extensions/issues/295
Upgrade nodejs version
----

fix: update node version

---

edge/cdk/extensions/prewarm/lambda/agent/agent.py
edge/cdk/extensions/prewarm/lambda/agent/test/requirements-test.txt
edge/cdk/extensions/prewarm/lambda/agent/test/test_agent.py
edge/cdk/extensions/prewarm/lambda/scheduler/scheduler.py
edge/cdk/extensions/prewarm/lambda/status_fetcher/status_fetcher.py
edge/cdk/extensions/prewarm/lambda/status_fetcher/test/requirements-test.txt
edge/cdk/extensions/prewarm/lambda/status_fetcher/test/test_status_fetcher.py

*Supporting both http/https when sending prewarm request to pop location*
*[x] Tested using cdk deploy in my test account*
----

[Feat] prewarm suppot https

---

docs-ig/en/api-reference-guide/extension-repository.md
docs-ig/en/extension-repository/pre-warming.md
docs-ig/en/revisions.md
docs-ig/zh/api-reference-guide/extension-repository.md
docs-ig/zh/extension-repository/pre-warming.md
edge/cdk/extensions/prewarm/README-cn.md
edge/cdk/extensions/prewarm/README.md

comment rollback

---

portal/src/pages/deploy/Deploy.tsx

feat: add default value in prewarm extension

---

edge/cdk/extensions/prewarm/prewarm-ext.ts
templates/console/source/lambda/config-version/cf_config_version_manager_graphql/cf_config_version_manager_graphql.py

bug fix about monitor

---

portal/src/components/styles/index.scss
portal/src/pages/monitor/comps/MonitorTable.tsx

fix: fix table url display issue when url is too long

---

templates/console/source/lambda/monitoring/non_realtime/metric_collector_by_cloudwatch/metric_collector_by_cloudwatch_for_tencent.py

Cust: add metrics for tencent

---

templates/console/source/lambda/monitoring/non_realtime/metric_collector_by_cloudwatch/metric_collector_by_cloudwatch_for_tencent.py

feat: bug fix

---

templates/console/source/lambda/monitoring/non_realtime/metric_collector_by_cloudwatch/metric_collector_by_cloudwatch_for_tencent.py

feat: fix data

---

templates/console/source/lambda/monitoring/non_realtime/metric_collector_by_cloudwatch/metric_collector_by_cloudwatch_for_tencent.py

feat: add metrics for tencent by cloudwatch
